version: 2.1
jobs:
  build:
    working_directory: ~/track-your-goals

    # Primary container image where all commands run

    docker:
      - image: cimg/ruby:3.1.2
        auth:
          username: arkniazi
          password: $DOCKERHUB_PASSWORD  # context / project UI env-var reference
        environment:
          PGHOST: localhost
          PGUSER: root
          RAILS_ENV: test
          RACK_ENV: test

    # Service container image available at `host: localhost`

      - image: cimg/postgres:14.6
        auth:
          username: arkniazi
          password: $DOCKERHUB_PASSWORD
        environment:
          POSTGRES_USER: ubuntu
          POSTGRES_DB: tyk
          POSTGRES_PASSWORD: ""

    steps:
      - checkout

      # Restore bundle cache
      - restore_cache:
          keys:
            - rails-demo-{{ checksum "Gemfile.lock" }}
            - rails-demo-

      # Bundle install dependencies
      - run:
          name: Install dependencies
          command: bundle install

      - run: sudo apt install -y postgresql-client || true

      # Store bundle cache
      - save_cache:
          key: rails-demo-{{ checksum "Gemfile.lock" }}
          paths:
            - vendor/bundle

      - run:
          name: Database Setup
          command: |
            bundle exec rake db:create
            bundle exec rake db:schema:load
          environment:
            DATABASE_URL: "postgres://ubuntu@localhost:5432/trk"

      - run:
          name: Parallel RSpec
          command: bin/rails test
          environment:
            DATABASE_URL: "postgres://ubuntu@localhost:5432/trk"
        
      - store_test_results:
          path: /tmp/test-results
