version: 2.1
jobs:
    build:
        working_directory: ~/track-your-goals
        docker:
            - image: circleci/ruby:3.1
              environment:
                RAILS_ENV: test
        steps:
          - checkout
          - run: bundle install
          - run: rspec